// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: inventory.proto

package inventorypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStockLevelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockLevelRequest) Reset() {
	*x = GetStockLevelRequest{}
	mi := &file_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockLevelRequest) ProtoMessage() {}

func (x *GetStockLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockLevelRequest.ProtoReflect.Descriptor instead.
func (*GetStockLevelRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *GetStockLevelRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type GetStockLevelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockQuantity int64                  `protobuf:"varint,1,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockLevelResponse) Reset() {
	*x = GetStockLevelResponse{}
	mi := &file_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockLevelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockLevelResponse) ProtoMessage() {}

func (x *GetStockLevelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockLevelResponse.ProtoReflect.Descriptor instead.
func (*GetStockLevelResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *GetStockLevelResponse) GetStockQuantity() int64 {
	if x != nil {
		return x.StockQuantity
	}
	return 0
}

var File_inventory_proto protoreflect.FileDescriptor

const file_inventory_proto_rawDesc = "" +
	"\n" +
	"\x0finventory.proto\x12\tinventory\"5\n" +
	"\x14GetStockLevelRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\">\n" +
	"\x15GetStockLevelResponse\x12%\n" +
	"\x0estock_quantity\x18\x01 \x01(\x03R\rstockQuantity2f\n" +
	"\x10InventoryService\x12R\n" +
	"\rGetStockLevel\x12\x1f.inventory.GetStockLevelRequest\x1a .inventory.GetStockLevelResponseB[ZYgithub.com/DragonZero000/Event-Driven-Order-Processing-System/proto/inventory;inventorypbb\x06proto3"

var (
	file_inventory_proto_rawDescOnce sync.Once
	file_inventory_proto_rawDescData []byte
)

func file_inventory_proto_rawDescGZIP() []byte {
	file_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)))
	})
	return file_inventory_proto_rawDescData
}

var file_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_inventory_proto_goTypes = []any{
	(*GetStockLevelRequest)(nil),  // 0: inventory.GetStockLevelRequest
	(*GetStockLevelResponse)(nil), // 1: inventory.GetStockLevelResponse
}
var file_inventory_proto_depIdxs = []int32{
	0, // 0: inventory.InventoryService.GetStockLevel:input_type -> inventory.GetStockLevelRequest
	1, // 1: inventory.InventoryService.GetStockLevel:output_type -> inventory.GetStockLevelResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_inventory_proto_init() }
func file_inventory_proto_init() {
	if File_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_proto_msgTypes,
	}.Build()
	File_inventory_proto = out.File
	file_inventory_proto_goTypes = nil
	file_inventory_proto_depIdxs = nil
}
