# docker/Dockerfile.payment
FROM golang:1.21-alpine

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /payment-service ./cmd/payment-service

EXPOSE 8081
EXPOSE 50052

CMD ["/payment-service"]