# docker/Dockerfile.inventory
FROM golang:1.21-alpine

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /inventory-service ./cmd/inventory-service

EXPOSE 8082
EXPOSE 50053

CMD ["/inventory-service"]