FROM golang:1.26.4-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /notification-service ./cmd/notification-service

FROM alpine:3.20

WORKDIR /app
COPY --from=builder /notification-service .

# gRPC порт
EXPOSE 50051
# Запуск
CMD ["./notification-service"]