# docker/Dockerfile.order
FROM golang:1.21-alpine

WORKDIR /app

# Копируем go.mod и go.sum
COPY go.mod go.sum ./
RUN go mod download

# Копируем исходники
COPY . .

# Сборка
RUN go build -o /order-service ./cmd/order-service

# Порт для health check
EXPOSE 8080

# gRPC порт
EXPOSE 50051

# Запуск
CMD ["/order-service"]