FROM golang:1.26.4-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /order-service ./cmd/order-service

FROM alpine:3.20

WORKDIR /app
COPY --from=builder /order-service .

# gRPC порт
EXPOSE 50051
# Запуск
CMD ["./order-service"]