FROM golang:1.26.4-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /inventory-service ./cmd/inventory-service

FROM alpine:3.20

WORKDIR /app
COPY --from=builder /inventory-service .

# gRPC порт
EXPOSE 50051
# Запуск
CMD ["./inventory-service"]